services:
  weatherstation:
    build: .
    container_name: weatherstation
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      MQTT_HOST: mqtt             # <-- SET YOUR MQTT BROKER HOST
      MQTT_PORT: 1883             # <-- Optional broker port
      MQTT_USER: user             # <-- Optional username
      MQTT_PASSWORD: pass         # <-- Optional password
      DEVICE_ID: weather_station  # <-- Device identifier
      DEVICE_NAME: "Backyard Weather"  # <-- Display name
      DEVICE_MANUFACTURER: VEVOR  # <-- Optional manufacturer
      DEVICE_MODEL: "7-in-1 Weather Station"  # <-- Optional model name
      # UNITS can be "metric" or "imperial". Default is metric
      UNITS: metric
      # forward data to Weather Underground
      WU_FORWARD: "false"
      # credentials for Weather Underground (optional)
      WU_USERNAME: wu-user
      WU_PASSWORD: wu-pass
